export const SouvenirsService = {
  getSouvenirsList(){
    return [
      {
        SouvenirsId:'1',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'2',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'3',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'4',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'5',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'6',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'7',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },{
        SouvenirsId:'8',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'9',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'10',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'11',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'12',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'13',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      },
      {
        SouvenirsId:'14',
        title:'党员纪念钢笔',
        imageUrl:'',
        price:88.8,
        stock:80,
        listingDate:'2023-12-11'
      }
    ]
  },

  getSouvenirsData(){
    return Promise.resolve(this.getSouvenirsList())
  }
}
